# Generated by Django 2.2.2 on 2021-01-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='eventDeadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='eventFrom',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='eventTo',
            field=models.DateTimeField(),
        ),
    ]
