# Generated by Django 2.2.2 on 2021-01-10 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_participantregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='id',
        ),
        migrations.RemoveField(
            model_name='participantregistration',
            name='id',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='eventId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='participantregistration',
            name='pId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
